# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.

common: &common
  adapter: mysql
  encoding: utf8
  socket: <%= `mysql_config --socket`.chomp %>
  username: <%= `whoami`.chomp %>
  password:

development:
  database: ocw_dev
  << : *common

preview:
  database: ocw_dev
  << : *common

test:
  database: ocw_test
  << : *common

production:
  database: ocw_prod
  << : *common
